import { library } from '@fortawesome/fontawesome-svg-core';

import {
  faPlus,
  faBars,
  faSlidersH,
  faPlusCircle,
  faMinusCircle,
  faWifi,
  faLevelUpAlt,
  faLevelDownAlt,
  faCog,
  faSearch,
  faTimes,
  faTimesCircle,
  faWallet,
  faSignOutAlt,
  faSignInAlt,
  faTachometerAlt,
  faTrophy,
  faUserAlt,
  faChevronUp,
  faChevronDown,
  faTimes,
  faCamera,
  faUnlock,
  faBriefcase,
  faInfoCircle,
  faEllipsisH,
  faCheck,
  faExclamationTriangle,
  faGlobe,
  faIdCardAlt,
  faDollarSign,
  faChartLine,
  faBolt,
  faLock,
  faArrowUp,
  faAngleDoubleUp,
  faExternalLinkAlt,
  faLink,
  faPaperclip,
  // no faRepeat
  faPuzzlePiece,
  // no faCalendarExclamation
  faSync,
  faUserFriends,
  faExpand
} from '@fortawesome/free-solid-svg-icons';

import {
  faBell,
  faClock,
  faListAlt,
  faFileArchive,
  faAddressCard,
  faComments,
  faComment,
  faCheckCircle,
  faEye,
  faStar,
  faCalendarAlt,
  faCalendarPlus,
  faFileAlt,
  faFrown,
  faEnvelope,
  faEdit
} from '@fortawesome/free-regular-svg-icons';

import {
  faTwitter,
  faFacebook,
  faReddit,
  faGithub,
  faLinkedin
} from '@fortawesome/fontawesome-free-brands';

library.add(
  faPlus,
  faBars,
  faSlidersH,
  faPlusCircle,
  faMinusCircle,
  faWifi,
  faLevelUpAlt,
  faLevelDownAlt,
  faCog,
  faSearch,
  faTimes,
  faTimesCircle,
  faWallet,
  faSignOutAlt,
  faSignInAlt,
  faTachometerAlt,
  faTrophy,
  faUserAlt,
  faChevronUp,
  faChevronDown,
  faTimes,
  faCamera,
  faUnlock,
  faBriefcase,
  faInfoCircle,
  faEllipsisH,
  faCheck,
  faExclamationTriangle,
  faGlobe,
  faIdCardAlt,
  faDollarSign,
  faChartLine,
  faBolt,
  faLock,
  faArrowUp,
  faAngleDoubleUp,
  faExternalLinkAlt,
  faLink,
  faPaperclip,
  // no faRepeat
  faPuzzlePiece,
  // no faCalendarExclamation
  faSync,
  faUserFriends,
  faExpand,
  faBell,
  faClock,
  faListAlt,
  faFileArchive,
  faAddressCard,
  faComments,
  faComment,
  faCheckCircle,
  faEye,
  faStar,
  faCalendarAlt,
  faCalendarPlus,
  faFileAlt,
  faFrown,
  faEnvelope,
  faEdit,
  faTwitter,
  faFacebook,
  faReddit,
  faGithub,
  faLinkedin
);
